export default {
    'HTML Table to Unicode Table': `<table border="1" cellspacing="1" cellpadding="1" style="width: 468px;"><tbody><tr><th scope="col"> <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>'s Request
    </th><th scope="col"> <a href="/wikis/the-legend-of-zelda-hd/Link" title="Link">Link</a>'s Task
    </th></tr><tr><td> 10 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a></td><td> Gather 10 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a></td></tr><tr><td> Find a Goron
    </td><td> Travel to <a href="/wikis/the-legend-of-zelda-hd/Southern_Mine" title="Southern Mine">Southern Mine</a> in the <a href="/wikis/the-legend-of-zelda-hd/Eldin" title="Eldin">Eldin</a> Region and speak to <b>Greyson</b>. He will only speak to you at night. He will then leave for <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a>. Return to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a> (bring 20&nbsp;<a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a>).
    </td></tr><tr><td> 20 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a></td><td> Gather 20 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a> and speak to&nbsp;<a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>.
    </td></tr><tr><td> Find a <a href="/wikis/the-legend-of-zelda-hd/Gerudo" class="mw-redirect" title="Gerudo">Gerudo</a></td><td> Travel to <a href="/wikis/the-legend-of-zelda-hd/Kara_Kara_Bazaar" title="Kara Kara Bazaar">Kara Kara Bazaar</a> in the <a href="/wikis/the-legend-of-zelda-hd/Gerudo_Wasteland" title="Gerudo Wasteland">Gerudo Wasteland</a> region and speak to <b>Rhondson</b> near the Inn. She will then leave for <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a>. Return to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a> (bring 30&nbsp;<a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a>).
    </td></tr><tr><td> 30 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a></td><td> Gather 30 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>.
    </td></tr><tr><td> Find a Rito
    </td><td> Travel to <a href="/wikis/the-legend-of-zelda-hd/Rito_Village" title="Rito Village">Rito Village</a> in the <a href="/wikis/the-legend-of-zelda-hd/Tabantha_Region" class="new" title="Tabantha Region (page does not exist)">Tabantha Region</a> and speak to <b>Fryson</b>. He's the blue Rito sitting on the lowest balcony. He will then leave for <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a>. Return to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a> (bring 50 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a>).
    </td></tr><tr><td> 50 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a></td><td> Gather 50 <a href="/wikis/the-legend-of-zelda-hd/Wood" title="Wood">wood</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>.
    </td></tr><tr><td> Find a Zora
    </td><td> Travel to <a href="/wikis/the-legend-of-zelda-hd/Zora%27s_Domain" title="Zora's Domain">Zora's Domain</a> in the <a href="/wikis/the-legend-of-zelda-hd/Lanayru_Region" class="new" title="Lanayru Region (page does not exist)">Lanayru Region</a> and speak to <b>Kapson</b>. He's standing behind the stairs to the king's room. He will then leave for <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a>. Return to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>.
    </td></tr><tr><td> Invite <b>Bolson</b> and <b>Karson</b></td><td> Travel to <a href="/wikis/the-legend-of-zelda-hd/Hateno_Village" title="Hateno Village">Hateno Village</a> in the <a href="/wikis/the-legend-of-zelda-hd/Hateno_Region" class="new" title="Hateno Region (page does not exist)">Hateno Region</a> and speak to <b>Bolson</b> and <b>Karson</b>. They are sitting in front of <a href="/wikis/the-legend-of-zelda-hd/Link" title="Link">Link</a>'s House, south of Firly Pond. They will then travel to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a>. Return to <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a> and speak to <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a>.
    </td></tr><tr><td> Attend <a href="/wikis/the-legend-of-zelda-hd/Hudson" title="Hudson">Hudson</a> and <b>Rhondson's</b> Wedding
    </td><td> Attend the wedding and receive your reward:<br>(3) Diamonds and a completed <a href="/wikis/the-legend-of-zelda-hd/Tarrey_Town" title="Tarrey Town">Tarrey Town</a></td></tr></tbody></table>`
}
